name: ğ— ğ—¨ğ—­ğ—”ğ— ğ— ğ—œğ—Ÿ_ğ— ğ——
services:
  - name: muzammil_md-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
